spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
  datasource:
    password: 9tong139
    username: MzkwOTQ4Y
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://172.19.0.203:3001/9tong_utils?useUnicode=yes&characterEncoding=UTF-8&useSSL=false